import { createElement } from "react";
import {
  AlertCircle,
  Archive,
  Bell,
  BookOpen,
  BriefcaseBusiness,
  CalendarDays,
  CalendarClock,
  CheckCircle2,
  Circle,
  ClipboardList,
  Coffee,
  Compass,
  Footprints,
  Gift,
  GraduationCap,
  Heart,
  HeartHandshake,
  Home,
  Info,
  Lightbulb,
  LoaderCircle,
  Mail,
  MapPin,
  MessageCircle,
  MessageSquareText,
  Minus,
  MoreHorizontal,
  Phone,
  Pin,
  RefreshCw,
  Share2,
  Shield,
  Star,
  TrendingDown,
  TrendingUp,
  User,
  UserRound,
  Users,
  UsersRound,
  Video,
  type LucideIcon,
  type LucideProps,
} from "lucide-react";
import type { IconIdentifier } from "@/lib/presentation/types";

const presentationIcons = {
  "alert-circle": AlertCircle,
  archive: Archive,
  bell: Bell,
  "book-open": BookOpen,
  "briefcase-business": BriefcaseBusiness,
  "calendar-days": CalendarDays,
  "calendar-clock": CalendarClock,
  "check-circle-2": CheckCircle2,
  circle: Circle,
  "clipboard-list": ClipboardList,
  coffee: Coffee,
  compass: Compass,
  footprints: Footprints,
  gift: Gift,
  "graduation-cap": GraduationCap,
  heart: Heart,
  "heart-handshake": HeartHandshake,
  home: Home,
  info: Info,
  lightbulb: Lightbulb,
  "loader-circle": LoaderCircle,
  mail: Mail,
  "map-pin": MapPin,
  "message-circle": MessageCircle,
  "message-square-text": MessageSquareText,
  minus: Minus,
  "more-horizontal": MoreHorizontal,
  phone: Phone,
  pin: Pin,
  "refresh-cw": RefreshCw,
  "share-2": Share2,
  shield: Shield,
  star: Star,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  user: User,
  "user-round": UserRound,
  users: Users,
  "users-round": UsersRound,
  video: Video,
} satisfies Record<IconIdentifier, LucideIcon>;

export function renderPresentationIcon(
  identifier: IconIdentifier,
  props: LucideProps,
) {
  return createElement(presentationIcons[identifier], props);
}
